### PR TITLE
Throttle web vitals recording to 10% of users

### PR DESCRIPTION
**Pull request by schamp**

### CODE REVIEW

**Comment by pnavarrc** [comment]
[Sample webvitals by session for 10% of sessions](https://trello.com/c/6URJ6bcj/1121-sample-webvitals-by-session-for-10-of-sessions)

**Comment by schamp** [comment]
>  [Sample webvitals by session for 10% of sessions](https://trello.com/c/6URJ6bcj/1121-sample-webvitals-by-session-for-10-of-sessions)

Thanks, I was wondering how to do this.  do I just copy a link to the task, or do I have to set up the integration?

**Comment by pnavarrc** [comment]
In Trello you can attach a PR to the ticket (sidebar under Power-Ups) — we are not really disciplined into linking the PR to the ticket, I do it to make it easier to see what's already in progress.

image

**Review by pnavarrc — APPROVED** [review]
Looks good!

**Pull request merged**
