### PR TITLE
Fix margin under Educational Resources

### PR DESCRIPTION
**Pull request by faihegberg**
This PR aligns the button wrapper styling under "Education Resources" with that of "About Us"

### CODE REVIEW

**Review by chasulin — COMMENTED** [review]
the footer has different alignment rules--i think this button should be centered in the footer on mobile like the set of buttons below it. right now its left aligned:

Screen Shot 2021-07-12 at 3 52 45 PM

**Comment by faihegberg** [comment]
> the footer has different alignment rules--i think this button should be centered in the footer on mobile like the set of buttons below it. right now its left aligned:
> 
> Screen Shot 2021-07-12 at 3 52 45 PM

@chasulin Should the "Educational Resources" heading be centered too?

**Comment by chasulin** [comment]
hmm yeah prob

**Comment by chasulin** [comment]
the middle section's header is now center aligned-

Screen Shot 2021-07-12 at 11 31 39 PM

**Comment by faihegberg** [comment]
> the middle section's header is now center aligned-
> 
> Screen Shot 2021-07-12 at 11 31 39 PM

🤦🏼‍♀️ Urgh! Should have caught that. On it!

**Review by chasulin — APPROVED** [review]

**Pull request merged**
