### PR TITLE
Add search by zip code to main page, state page. closes #304

### LINKED ISSUE #304: Add search by zip code to main page, state page
As an improvement to #303, some users may not know their county, but they likely know their zip code, so we should allow them to enter their zip code and jump into the county.

### PR DESCRIPTION
**Pull request by apeterson7**
This PR adds support for county search by zip code.   It includes a csv procured from HUD along with a script for converting it into a json map of county fip codes to overlapping zip codes (some zip codes cover more than one county).

Screen Shot 2020-08-18 at 4 47 25 PM
Screen Shot 2020-08-18 at 4 49 13 PM

### CODE REVIEW

**Comment by mikelehen** [comment]
Wow!  Thanks so much for submitting this.  We'll take a look and try to get this merged / shipped soon!

Just an FYI- our github issues list isn't super up-to-date.  If you're interested in getting more involved in the project, let me know and I can try to provide some guidance. 😁

**Comment by apeterson7** [comment]
@mikelehen Thanks for reviewing it!  I'd love to get more involved in the project - let me know!

**Comment by mikelehen** [comment]
@apeterson7 Great to hear!

We have moved to Trello for most of our bug / feature tracking.  You can see the board here: https://trello.com/b/zLf79HJ8/public-engpmux It's a bit messy at the moment (a bunch of untriaged issues) but "Eng Backlog" or "Eng Prioritized" are good places to look.  If you see something that catches your eye, maybe shoot me an email (michael@covidactnow.org) and I can advise you on it.  

One particular one that would be nice to tackle is https://trello.com/c/O9nRsq19/358-implement-new-new-cases-tool-tip It will probably require a bit of plumbing work though to maybe change `caseDensityByCases` here https://github.com/covid-projections/covid-projections/blob/32bdab80c11188e3857c7c22759e351b7619a62f/src/common/models/Projection.ts#L238 to something like `caseDensityData` and make it an object containing `{ caseDensity: ... , cases: ... }` and having the chart pull those values out to create both the graph and the tooltip.  If that seems too confusing, no worries. I can help you find something else to tackle. 😁

**Comment by apeterson7** [comment]
@mikelehen I'll take a look at the tool tip issue!  Can I assign myself the ticket on the trello board?

**Pull request merged**
