### PR TITLE
Remove invalid override from MuiSwitch

### PR DESCRIPTION
**Pull request by schamp**
MUI was complaining about this.

### CODE REVIEW

**Comment by schamp** [comment]
this might not be quite right

**Comment by pnavarrc** [comment]
It looks like the switch component works with this change, however, `MuiSwitch` inherits from `IconButton` which in turns inherits from `ButtonBase`, and [`focusVisible` is a customizable property for `ButtonBase`](https://material-ui.com/api/button-base/#css), so I don't think is necessarily incorrect.

**Review by chasulin — APPROVED** [review]
focus state still works, so i think this is fine

Screen Shot 2021-03-02 at 10 39 56 AM

**Comment by schamp** [comment]
thanks for having a look.  there were actually additional warnings related to this change, and to eliminate them I removed some additional things that I haven't incorporated into this PR yet.   and I was digging into something else and haven't had time to test, so I want to revisit this later.

**Comment by schamp** [comment]
I've lost context on this, so will abandon.  I may try again later.

**Pull request closed without merging**
