### PR TITLE
Add lines for when hospitals are overwhelmed at each level of intervention

### PR DESCRIPTION
**Pull request by gsoltis**
Feedback on UI is especially welcome, as that is not my strong suit. 

CA

With an intervention disabled:
CA_one_disabled

### CODE REVIEW

**Comment by zjrosen1** [comment]
Jeremy is already got a pr for this

Screen Shot 2020-03-26 at 9 40 02 PM

**Comment by zjrosen1** [comment]
@jugglerjer you should look at the plot lines toggle though

**Comment by jugglerjer** [comment]
Oooh, is this the ability to turn certain plot lines on and off?

**Comment by igorkofman** [comment]
We don't want to show multiple lines at the same time, do we?  Can we only
show the yellow line on yellow graph hover?

**Comment by gsoltis** [comment]
I didn't see an easy way to do it based on hover. There are mouse over and mouse out events, but i think the logic for when an area is highlighted is a little more complex. You can have states where nothing is hovered but everything is 'inactive', as well as obviously states where everything is active.

I decided to go with showing multiple lines to try to communicate the difference an intervention could have, but it definitely does make it more cluttered.

**Comment by gsoltis** [comment]
Code for toggling is here: https://github.com/covid-projections/covid-projections/pull/227/files#diff-50783417df68929923f38ce05707e08cR104

It's relatively easy to do as long as the plotlines have names. The hard part is knowing when to do it. Hiding and showing a series is easy to watch, other state transitions are more difficult.

**Comment by zjrosen1** [comment]
@igorkofman we are only showing today and the intervention line, and Jeremy already has the correct intervention line showing based on states current intervention

**Pull request closed without merging**
