### PR TITLE
Set up husky pre-commit hook to fix formatting / lint on staged files before committing.

### PR DESCRIPTION
**Pull request by mikelehen**
https://trello.com/c/gQdgpH03/86-set-up-git-hook-for-linting

### CODE REVIEW

**Comment by mikelehen** [comment]
[Set up git hook for linting](https://trello.com/c/gQdgpH03/86-set-up-git-hook-for-linting)

**Comment by pnavarrc** [comment]
Should we run prettier too?

**Comment by mikelehen** [comment]
It turns out lint-staged does it automatically based on our [.eslintrc.js](https://github.com/covid-projections/covid-projections/blob/47efa026cdba50781e1e3343972da7aac7b12187/.eslintrc.js#L9)

**Comment by mikelehen** [comment]
The `husky` npm package automatically sets up the git hooks for you, as opposed to having to make everybody manually set up the git hooks themselves (and of course not everybody will, and then we'll still have develop get broken a couple times a week).

**Pull request merged**
