### PR TITLE
WIP nextjs prototype

### PR DESCRIPTION
**Pull request by schamp**
This is a big mess for statically generating the site via next.js.  It would be a major platform change, with a lot of implications especially around routing and how we do internal linking.  However, I believe that the way it does static generation of dynamic routes is pretty promising.

This is hardly optimized and has only two routes (about and contact) migrated, with lots of hacks in there.  Next up I'll try some of the dynamic location-based routes and the data extraction, to see what gains there are to be had in rendering and deferred loading.

### CODE REVIEW

**Comment by schamp** [comment]
totally unscientific comparison, before any optimization or fine-tuning:
before: https://developers.google.com/speed/pagespeed/insights/?url=https://www.covidactnow.org/about
after: https://developers.google.com/speed/pagespeed/insights/?url=https://covid-projections-git-features-next-js.covidactnow.vercel.app/about

**Comment by schamp** [comment]
just updated, now statically generates all state pages and metro area pages

**Comment by schamp** [comment]
export log:
`$ time yarn build
yarn run v1.22.10
$ next build && next export -o build
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version
info  - Creating an optimized production build...
info  - Using external babel configuration from F:\src\covid-projections-next\.babelrc
info  - Compiled successfully
info  - Collecting page data...
info  - Generating static pages (0/448)
info  - Generating static pages (112/448)
info  - Generating static pages (224/448)
info  - Generating static pages (336/448)
info  - Generating static pages (448/448)
info  - Finalizing page optimization...

Page                                                           Size     First Load JS
┌ ○ /                                                          266 B           551 kB
├   /_app                                                      0 B             551 kB
├ ○ /404                                                       3.46 kB         554 kB
├ ○ /about                                                     13.2 kB         905 kB
├ ● /us/[stateId]                                              317 B          1.11 MB
├   ├ /us/alabama-al
├   ├ /us/alaska-ak
├   ├ /us/arizona-az
├   └ [+50 more paths]
└ ● /us/metro/[metroAreaUrlSegment]                            330 B          1.11 MB
    ├ /us/metro/abilene_tx
    ├ /us/metro/aguadilla-isabela_pr
    ├ /us/metro/akron_oh
    └ [+389 more paths]
+ First Load JS shared by all                                  551 kB
  ├ chunks/13bcd3086900f2e772538b746cd85e2916035971.ad352d.js  438 kB
  ├ chunks/29107295.32a075.js                                  24.5 kB
  ├ chunks/75fc9c18.9c9104.js                                  19.2 kB
  ├ chunks/ef389e0dd3c65da4f1c11a8e044061ce4f99f8cb.3185c5.js  13.1 kB
  ├ chunks/framework.4773e3.js                                 40.2 kB
  ├ chunks/main.f0be83.js                                      6.62 kB
  ├ chunks/pages/_app.bb61c3.js                                7.51 kB
  ├ chunks/webpack.111509.js                                   1.38 kB
  └ css/a96166d16fc7e22b7c01.css                               686 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

info  - using build directory: F:\src\covid-projections-next\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 3 workers
info  - Exporting (0/3)
info  - Copying "public" directory
info  - Exporting (3/3)
Export successful. Files written to F:\src\covid-projections-next\build
Done in 176.02s.

real    3m0.075s
user    0m0.045s
sys     0m0.242s
$ du -hs build/
133M    build/
`

**Comment by pnavarrc** [comment]
Closing to clean up our PRs, labelling it with performance to make it easier to find!

**Pull request closed without merging**
