### PR TITLE
Typescript conversion

### PR DESCRIPTION
**Pull request by schamp**
Convert a few lingering files to typescript and clean up a few type errors.  This will smooth the way for more static generation stuff, and is a good idea anyway (found a few small bugs).

It does touch a lot of stuff so if you feel like bashing on it a bit to make sure I didn't miss anything I'd appreciate that.

### CODE REVIEW

**Comment by pnavarrc** [comment]
Thanks for tackling this @schamp! I think this PR is too big to be reviewed and tested as a single unit, is there an obvious way to split it? Otherwise I might cherry-pick changes from here into smaller PRs so we can merge with confidence.

**Comment by schamp** [comment]
sure, I could try splitting it up.  let me take a stab at that tonight.

**Comment by schamp** [comment]
if I can isolate pure type-only changes (vs. ones that affect behavior) I'm sure that'd make it easier.

**Comment by schamp** [comment]
split into a number of other smaller PRs, so abandoning this one.

**Pull request closed without merging**
