### PR TITLE
Light blue selector for county

### PR DESCRIPTION
**Pull request by adpirz**
image
image

### CODE REVIEW

**Comment by mikelehen** [comment]
Nice!  Though I'm a little loathe to introduce a new color.  When I look at the examples you pasted, it's not at all obvious that blue represents selection and the other two colors convey information about the counties.  Iowa is kind of extra bad because so few counties have colors, but even with WA, the blue doesn't jump out at me as "the selected county."

image

I suck at UX though so I'm not sure exactly what I'd want to see.  Out of curiosity, did you play around with any other approaches? Like just use opacity to convey selection?  But maybe the two different tones of grey are problematic.  Can we just outline the selected county in solid black or something?

**Comment by igorkofman** [comment]
@yvonne - our new designer who owns this area is +1 on outline.  can we try that?

**Comment by adpirz** [comment]
So outline was my first option, but the problem with outline is there's no clean way to keep the outline on top, see results:

image
image

**Comment by jwparktom** [comment]
What about darker gray color for counties with gray color and 0.5 opacity for counties with non-gray color? I tried it in #593

**Comment by igorkofman** [comment]
@jwparktom - in our version a selected county with not enough data looks just like de-selected counties with no data at all:
https://www.dropbox.com/s/1rndkd9cav5vp4d/Screenshot%202020-04-26%2000.30.27.png?dl=0

Which is also true in prod

**Comment by igorkofman** [comment]
@adpirz oh yea, that doesn't look so hot.  What about making selected county a dark gray either always (regardless of initial color) or if it's dark gray.

**Comment by jwparktom** [comment]
@igorkofman Working for me... that's weird. Wrong link, maybe?
https://ibb.co/rtTVqf6
https://ibb.co/Np6LYBs

**Comment by igorkofman** [comment]
https://covid-projections-git-fork-jwparktom-aesthetic-changes.covidactnow.now.sh/us/ca/county/inyo_county is where i was looking, but must be the wrong place!

**Comment by jwparktom** [comment]
@igorkofman Oops, my bad :) Should be good now.

**Comment by igorkofman** [comment]
Still not working for me on your branch, but I think visually it's probably right (hover state becomes permanent)

**Comment by mikelehen** [comment]
I think this is obsolete now (we implemented a black outline).

**Pull request closed without merging**
