### PR TITLE
remove share and re-order newsletter

### PR DESCRIPTION
**Pull request by schamp**
Here's what it looks like, per https://trello.com/c/1G1dGPrA/251-remove-share-embed-shuffle-partners-in-hp

image

### CODE REVIEW

**Comment by schamp** [comment]
[Remove share embed / shuffle partners in HP](https://trello.com/c/1G1dGPrA/251-remove-share-embed-shuffle-partners-in-hp)

**Comment by schamp** [comment]
This left some things unused, which I tried to find and remove.  Some refactoring of the not-all-that-useful layers might be in order here.

**Review by faihegberg — COMMENTED** [review]
This looks good! Although like Josh mentioned in the card, the spacing for the Alert sign-up on other pages are now off for mobile and desktop view. This should be good to go once this is addressed 👍🏼 

image

**Review by faihegberg — APPROVED** [review]
LGTM!

**Pull request merged**
