### PR TITLE
Slim header

### PR DESCRIPTION
**Pull request by adpirz**
image

image

### CODE REVIEW

**Comment by zjrosen1** [comment]
where did we land with showing the intervention in the header?

**Comment by zjrosen1** [comment]
Also Jermey Lubin is looking into redesigning it

**Comment by adpirz** [comment]
@zjrosen1 Jumana mentioned Jeremy was working on placing it elsewhere

**Comment by crwilcox** [comment]
https://github.com/covid-projections/covid-projections/pull/184 is modifying the call to action as well.

**Comment by mikelehen** [comment]
I merged #184.  It adds a mention of the current intervention to the call-to-action.  I think we probably still want to highlight it in other places.

One suggestion that came up last night and I'm not sure if/where it's being tracked / worked-on is to change the chart so the trend for the current intervention is highlighted (as if you were hovering over it) automatically.  @adpirz Were you going to look into that?

**Comment by adpirz** [comment]
@mikelehen Will look into that today

**Pull request merged**
