### PR TITLE
Adding API + Spreadsheet links to FAQ

### PR DESCRIPTION
**Pull request by jamestamplin**
If someone can run this locally, I'd appreciate them checking the spacing between links and words 

I need to install yarn...

cc @adpirz

### CODE REVIEW

**Comment by adpirz** [comment]
Pushed a change, breaking tag wasn't closed and spacing was off, final product: 
image

**Comment by jamestamplin** [comment]
thanks man!

James Tamplin
tinyletter.com/jamest (2-3 emails / yr on what I'm up to)

**Comment by jamestamplin** [comment]
@adpirz anything left to do before merging this?

**Comment by jamestamplin** [comment]
actually, never-mind, this looks like it's changed in the new site layout. I'll close this.

**Pull request closed without merging**
