### PR TITLE
Add deploy-s3.sh deploy script.

### PR DESCRIPTION
**Pull request by mikelehen**
Deploys files to S3 in an ideal order and with appropriate Cache-Control headers via new deploy-s3.sh script.

https://trello.com/c/DaqD8LZ2/745-performance-update-caching-policy-for-static-assets
https://trello.com/c/1Mv1iYL3/718-improve-website-deploy-atomicity-caching-problems-website-fails-to-load-after-a-deploy

### CODE REVIEW

**Review by ghop02 — APPROVED** [review]
This looks great to me!

**Review by pnavarrc — APPROVED** [review]
Looks good!

**Comment by mikelehen** [comment]
[Improve website deploy atomicity / caching problems (website fails to load after a deploy)](https://trello.com/c/1Mv1iYL3/718-improve-website-deploy-atomicity-caching-problems-website-fails-to-load-after-a-deploy)

**Comment by mikelehen** [comment]
[Performance - Update caching policy for static assets](https://trello.com/c/DaqD8LZ2/745-performance-update-caching-policy-for-static-assets)

**Pull request merged**
