### PR TITLE
issue 93 remove chartjs code 

### PR DESCRIPTION
**Pull request by sarabpj**
[Issue 93: removing chart.js code](https://github.com/covid-projections/covid-projections/issues/93)
Remove chart.js from package.json, package-lock.json, and yarn.lock

### CODE REVIEW

**Comment by szhu** [comment]
Hey @sarabpj @zjrosen1!

Even after this PR, `src/screens/ModelPage/ModelPage.js` still has:

https://github.com/covid-projections/covid-projections/blob/2e4033958c29e8ae53e822f0ccac7c65bf816dc2/src/screens/ModelPage/ModelPage.js#L3

And I can't run this site because I get:

image

**Comment by zjrosen1** [comment]
Already fixed in develop

**Comment by szhu** [comment]
ffddf6b7fdb26282f19d176cf8682214a690b363 fixes this

**Comment by sarabpj** [comment]
@szhu  sorry about that @zjrosen1 thank you!

**Pull request merged**
